Update Build_iStoreOS_Debug.yml

diff --git a/.github/workflows/Build_iStoreOS_Debug.yml b/.github/workflows/Build_iStoreOS_Debug.yml
--- a/.github/workflows/Build_iStoreOS_Debug.yml
+++ b/.github/workflows/Build_iStoreOS_Debug.yml
@@ -213,7 +213,14 @@ jobs:
         cd openwrt
         echo -e "$(nproc) thread compile"
         echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
-        make -j$(nproc) || make -j1 || make -j1 V=s
+        set +e  # 禁用自动失败
+        make -j$(nproc) || {
+          echo "::warning::第一次编译失败，尝试单线程编译";
+          make -j1 || {
+            echo "::error::编译失败";
+            exit 1;
+          }
+        }
         echo "::set-output name=status::success"
 
     - name: 检查磁盘空间
