Update Build_iStoreOS_Debug.yml

diff --git a/.github/workflows/Build_iStoreOS_Debug.yml b/.github/workflows/Build_iStoreOS_Debug.yml
--- a/.github/workflows/Build_iStoreOS_Debug.yml
+++ b/.github/workflows/Build_iStoreOS_Debug.yml
@@ -249,11 +249,11 @@ jobs:
           echo "::error::❌ 设置 REVISION 失败"
           exit 1
         }
-        # 替换所有 $(REVISION) 引用
-        sed -i "s/\$(REVISION)/\${date_version}/g" "$VERSION_MK" || {
-          echo "::error::❌ 替换 REVISION 引用失败"
-          exit 1
-        }
+        # # 替换所有 $(REVISION) 引用
+        # sed -i "s/\$(REVISION)/\${date_version}/g" "$VERSION_MK" || {
+        #   echo "::error::❌ 替换 REVISION 引用失败"
+        #   exit 1
+        # }
         
         # 修改 image-config.in
         IMAGE_CONFIG="package/base-files/image-config.in"
@@ -267,15 +267,15 @@ jobs:
           exit 1
         }
         
-        # 提取主版本号
-        VERSION_NUMBER=$(awk -F '[ ,]' '/VERSION_NUMBER:=/ {for(i=1; i<=NF; i++) {if ($i ~ /[0-9]+\.[0-9]+\.[0-9]+/) {gsub(/[^0-9.]/, "", $i); print $i; exit}}}' "$VERSION_MK")
+        # # 提取主版本号
+        # VERSION_NUMBER=$(awk -F '[ ,]' '/VERSION_NUMBER:=/ {for(i=1; i<=NF; i++) {if ($i ~ /[0-9]+\.[0-9]+\.[0-9]+/) {gsub(/[^0-9.]/, "", $i); print $i; exit}}}' "$VERSION_MK")
         
-        # 调整固件命名规则
-        IMAGE_MK="include/image.mk"
-        sed -i "s|DEVICE_IMG_PREFIX := \$(IMG_PREFIX)-\$(1)|DEVICE_IMG_PREFIX := \$(IMG_PREFIX)-${VERSION_NUMBER}-${date_version}-\$(1)|" "$IMAGE_MK" || {
-          echo "::error::❌ 修改固件前缀失败"
-          exit 1
-        }
+        # # 调整固件命名规则
+        # IMAGE_MK="include/image.mk"
+        # sed -i "s|DEVICE_IMG_PREFIX := \$(IMG_PREFIX)-\$(1)|DEVICE_IMG_PREFIX := \$(IMG_PREFIX)-${VERSION_NUMBER}-${date_version}-\$(1)|" "$IMAGE_MK" || {
+        #   echo "::error::❌ 修改固件前缀失败"
+        #   exit 1
+        # }
         
         # 修改系统描述信息
         author="Loki"
